language: python
sudo: false

cache: pip

branches:
  only:
    - master

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"

script:
  - "tox"
