language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=lint

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"

script:
  - "tox"
