language: python
sudo: false

python: 3.6

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOXENV=py36
    - env: TOXENV=lint

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"

script:
  - "tox"
